In [11]:
include("julia_ref/code_00_Lattice.jl")
include("julia_ref/code_01_FiniteLattice.jl")
include("julia_ref/code_10_InteractionMatrix.jl")
include("julia_ref/code_20_ManyBodyHamiltonian.jl")

ManyBodyHamiltonian_MK_2V1B_2B_col (generic function with 1 method)

In [ ]:
function FiniteTriangularLattice(lattice::Lattice, u11::Int64, u12::Int64, u21::Int64, u22::Int64; isTRS::Bool=true, α1::Float64=0.0, α2::Float64=0.0, eps::Float64=1.0e-9)::FiniteLattice

    # check for structure of u matrix
    # siteNum = u11*u22 - u12*u21

    # L1 = gcd(u11, u12)
    # L2 = gcd(u21, u22)

    # if siteNum != L1*L2
    #     println("**warning: FiniteLattice does not satisfy necessary arithmetic operations**")
    # end

    # boundary vectors
    vecL1 = u11*lattice.a1 + u12*lattice.a2
    vecL2 = u21*lattice.a1 + u22*lattice.a2

    # finite lattice area
    area_UC = cross([lattice.a1; 0], [lattice.a2; 0])[3]
    area_FL = cross([vecL1; 0], [vecL2; 0])[3]
    
    # momentum grid lattice vectors
    g1 = (2*π/area_FL)*[+vecL2[2], -vecL2[1]]
    g2 = (2*π/area_FL)*[-vecL1[2], +vecL1[1]]
    
    # Brillouin zone grid
    BZ0 = [zeros(Float64, 2) for ik in 0:siteNum-1]
    BZu = [zeros(Float64, 2) for ik in 0:siteNum-1]
    BZd = [zeros(Float64, 2) for ik in 0:siteNum-1]
    for ik1 in 0:L1-1, ik2 in 0:L2-1
        
        ik = ik1 + L1*ik2
        k0 = ik1*g1 + ik2*g2
        ku = (ik1+α1)*g1 + (ik2+α2)*g2
        kd = (ik1-α1)*g1 + (ik2-α2)*g2
        
        # modulo reciporcal lattice vectors
        f1 = dot(k0, lattice.a1)/(2*π)
        f2 = dot(k0, lattice.a2)/(2*π)
        f1 = f1 - floor(f1 + eps)
        f2 = f2 - floor(f2 + eps)
        k0 = f1*lattice.Q1 + f2*lattice.Q2
        
        f1 = dot(ku, lattice.a1)/(2*π)
        f2 = dot(ku, lattice.a2)/(2*π)
        f1 = f1 - floor(f1 + eps)
        f2 = f2 - floor(f2 + eps)
        ku = f1*lattice.Q1 + f2*lattice.Q2
        
        f1 = dot(kd, lattice.a1)/(2*π)
        f2 = dot(kd, lattice.a2)/(2*π)
        f1 = f1 - floor(f1 + eps)
        f2 = f2 - floor(f2 + eps)
        kd = f1*lattice.Q1 + f2*lattice.Q2
        
        BZ0[1+ik] = k0
        BZu[1+ik] = ku
        BZd[1+ik] = (isTRS ? kd : ku)
    end
    
    return FiniteLattice(lattice, u11, u12, u21, u22, siteNum, L1, L2, vecL1, vecL2, g1, g2, BZ0, isTRS, α1, α2, BZu, BZd)
end

In [12]:
tl = TriangularLattice()
fl = FiniteLattice(tl, 6, 3, 3, 6)
Qs = FiniteReciprocalLattice(tl, 32)

**warning: FiniteLattice does not satisfy necessary arithmetic operations**


2977-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [7.255197456936871, 0.0]
 [3.6275987284684357, 6.283185307179586]
 [-3.6275987284684357, 6.283185307179586]
 [-7.255197456936871, -0.0]
 [-3.6275987284684357, -6.283185307179586]
 [3.6275987284684357, -6.283185307179586]
 [14.510394913873743, 0.0]
 [10.882796185405308, 6.283185307179586]
 [7.255197456936871, 12.566370614359172]
 ⋮
 [192.2627326088271, -56.548667764616276]
 [195.89033133729552, -50.26548245743669]
 [199.51793006576398, -43.982297150257104]
 [203.1455287942324, -37.69911184307752]
 [206.77312752270083, -31.41592653589793]
 [210.40072625116926, -25.132741228718345]
 [214.02832497963772, -18.84955592153876]
 [217.65592370810614, -12.566370614359172]
 [221.28352243657457, -6.283185307179586]

In [13]:
ff_Lambda = FormFactors_IdealChernBand_1V(fl, Qs, 0.4, 0)

2977-element Vector{Matrix{ComplexF64}}:
 [0.9999999999999997 - 7.945636494545275e-34im 0.2920917755831912 + 0.02997775429351259im … 0.9999999999999997 - 7.945636494545275e-34im 0.9999999999999997 - 7.945636494545275e-34im; 0.2920917755831912 - 0.029977754293512602im 0.9999999999999987 + 1.734723889576579e-18im … 0.2920917755831912 - 0.029977754293512602im 0.2920917755831912 - 0.029977754293512602im; … ; 0.9999999999999997 - 7.945636494545275e-34im 0.2920917755831912 + 0.02997775429351259im … 0.9999999999999997 - 7.945636494545275e-34im 0.9999999999999997 - 7.945636494545275e-34im; 0.9999999999999997 - 7.945636494545275e-34im 0.2920917755831912 + 0.02997775429351259im … 0.9999999999999997 - 7.945636494545275e-34im 0.9999999999999997 - 7.945636494545275e-34im]
 [-0.09965530882253845 - 3.588374316410151e-17im 0.1605188805746234 - 0.3078559378026797im … -0.09965530882253845 - 3.588374316410151e-17im -0.09965530882253845 - 3.588374316410151e-17im; 0.050838763317148414 - 0.01590330849009364

In [7]:
K_ff = length(ff_Lambda)
(N, M) = size(ff_Lambda[1]) # 첫 번째 요소의 shape를 가져옵니다.

ff_Lambda_3d = Array{ComplexF64, 3}(undef, K_ff, N, M)
for i in 1:K_ff
    ff_Lambda_3d[i, :, :] = ff_Lambda[i]
end

# 2. Qs (K_q x L) 배열 생성
K_qs = length(Qs)
L = length(Qs[1]) # 첫 번째 요소의 길이를 가져옵니다.

Qs_2d = Array{Float64, 2}(undef, K_qs, L)
for i in 1:K_qs
    Qs_2d[i, :] = Qs[i] # 각 벡터를 '행'으로 할당합니다.
end

In [8]:
wg = calculate_wg_FFT(fl, Qs, 0.4)

2977-element Vector{ComplexF64}:
      1.0397657539658913 + 0.0im
     0.12619634058689863 + 2.1348618402597386e-17im
      0.1261963405868986 + 1.3323828260310144e-17im
     0.12619634058689905 + 2.1368100160384235e-17im
     0.12619634058689863 - 2.1348618402597386e-17im
      0.1261963405868986 - 1.3323828260310144e-17im
     0.12619634058689905 - 2.1368100160384235e-17im
   0.0076595345315801575 - 1.7716541124770946e-17im
    0.013828348395201591 - 1.145188544687814e-18im
     0.00765953453158003 - 1.2624179045878092e-17im
                         ⋮
  -1.565316886525947e-17 - 1.0279591847878189e-17im
   8.447290176377686e-17 + 1.6086849734253672e-17im
   7.104234735211268e-17 + 2.878556767949014e-17im
 -1.1409872612694327e-16 - 4.458781434346637e-18im
  -3.676800617441467e-17 + 5.2123019442240626e-17im
   6.497081518619385e-17 - 4.2439738789229464e-17im
   8.464908461680576e-17 + 1.269465218708965e-16im
  -1.339802834648962e-16 - 1.330316065639714e-16im
   6.715277205832093e-17 - 1

In [9]:
using HDF5
h5path = "/home/cwpark/acband-laughlin-instability/data/h5/julia_ref_fixed.h5"
h5write(h5path, "ff_Lambda", ff_Lambda_3d)
h5write(h5path, "Qs", Qs_2d)
h5write(h5path, "wg", wg)
h5write(h5path, "BZ0", stack(fl.BZ0))
h5write(h5path, "BZu", stack(fl.BZu))
h5write(h5path, "BZd", stack(fl.BZd))

ErrorException: cannot create dataset: object "ff_Lambda" already exists at /

In [10]:
BZu = fl.BZu

27-element Vector{Vector{Float64}}:
 [-0.0, 0.0]
 [-4.030665253853817, -4.188790204786391]
 [-4.433731779239199, -2.0943951023931957]
 [-4.030665253853817, 4.188790204786391]
 [-0.8061330507707634, 0.0]
 [-1.2091995761561447, 2.094395102393195]
 [-4.433731779239199, 2.0943951023931957]
 [-1.2091995761561447, -2.094395102393195]
 [-1.6122661015415267, 0.0]
 [0.0, 0.0]
 ⋮
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]
 [0.0, 0.0]

In [ ]:
ff_Lambda[1].size

In [ ]:
Qs

In [ ]:
typeof(Qs)

In [ ]:
using Plots

x = [v[1] for v in Qs]  # 첫 번째 열
y = [v[2] for v in Qs]  # 두 번째 열

scatter(x, y,
        xlabel = "x",
        ylabel = "y",
        title  = "2D Coordinates Scatter",
        legend = false,
        aspect_ratio = :equal
)    

In [ ]:
ENV["JULIA_PYTHONCALL_EXE"] = "/home/cwpark/acband-laughlin-instability/.venv/bin/python"
using PythonCall

In [ ]:
sys = pyimport("sys")
project_root = pwd()
if pyconvert(Bool, project_root in sys.path) == false
    # sys.path.insert(0, path) 는 리스트의 맨 앞에 경로를 추가합니다.
    sys.path.insert(0, project_root)
end

In [ ]:
partial = pyimport("functools").partial
np = pyimport("numpy")
Lattice2D = pyimport("src.qm_utils.lattice.lattice").Lattice2D
acband = pyimport("src.acband")
acband_form_factors = acband.acband_form_factors
K_func1 = acband.K_func1

construct_brillouin_zones = pyimport("brillouin_zones").construct_brillouin_zones

In [ ]:
N_s = 27
K = 0.4

sqrt3 = sqrt(3)
lB = 1.0
a_M = sqrt((4 * π) / sqrt3) * lB

fourier_resolution = 256
G_radius = 64
V1 = 1.0
v1 = 3 * V1 * (a_M ^ 4) / (4 * π)

e1 = np.array([1, 0])
e2 = np.array([0, 1])
a1 = a_M * e2
a2 = a_M * ((-sqrt3 / 2) * e1 + (1 / 2) * e2)
lattice = Lattice2D(np.stack([a1, a2]))
recip_lattice = lattice.reciprocal()

In [ ]:
ff_Lambda_np = np.array(ff_Lambda)

np.save("ff_Lambda.npy", ff_Lambda_np)

In [ ]:
Qs_np = np.array(Qs)
np.save("Qs.npy", Qs)

In [ ]:
bz = construct_brillouin_zones(lattice)

bz_N_s = bz[N_s]

A = N_s * lattice.unit_cell_area

function V(q)
    return -v1 * np.linalg.norm(q, axis=-1) ^ 2
end

b1, b2 = lattice.reciprocal_lattice_vectors
b3 = -(b1 + b2)

K_func_args = (K, b1, b2, b3)
K_func = partial(K_func1, args=K_func_args)

G_coords, ac_ff = acband_form_factors(
    bz[N_s],
    lB,
    K_func,
    fourier_resolution,
    G_radius=G_radius
)